### ISSUE TITLE
[feature request] format shell script block using shfmt?

### ISSUE THREAD

**Issue by y9c** [snakemake/snakefmt#170]
How about wrap shfmt (https://github.com/mvdan/sh) to format shell script blocks. It can avoid trouble that an extra space causes the snakemake to re-run the code.

Snakemake now re-run pipeline by default when code changed. But it does not detect the content of the code. Thus, even an empty space or an indent is added, the pipeline will be re-run. But if shfmt can standardize the code. This problem can be avoided.

**Comment by mbhall88** [comment]
Thanks for the request. I don't think formatting people's shell scripts is within the scope of this project. Additionally, this would add an external dependency to snakefmt, which I dont think is necessary.

**Comment by mbhall88** [comment]
## Problem Statement

The user is facing a problem where Snakemake `shell` directives are not formatted by `snakefmt`. They want `snakefmt` to format shell code within these directives using `shfmt` to improve readability and maintainability.

## Solution

Integrate `shfmt` formatting into `snakefmt` for `shell` directives. We will use the `shfmt-py` package as a hard dependency to provide the `shfmt` executable without requiring the user to install external Go binaries. `snakefmt` will automatically detect `shell` directives, temporarily mask Snakemake variables (e.g., `{input}`), format the shell code, and unmask the variables. A CLI option `--no-shell-format` will be provided to opt-out.

## User Stories

1. As a `snakefmt` user, I want `shell` directives in my Snakemake rules to be automatically formatted, so that my shell code is consistent and readable.
2. As a `snakefmt` user, I want `shfmt` to be installed automatically when I install `snakefmt`, so that I don't have to manage external Go dependencies.
3. As a `snakefmt` user, I want Snakemake variables like `{input}` and `{output}` to be preserved during shell formatting, so that my workflows remain functional.
4. As a `snakefmt` user, I want escaped double braces `{{` and `}}` to be preserved and correctly handled during formatting, so that inline tools like `awk` work correctly.
5. As a `snakefmt` user, I want the ability to opt-out of shell formatting using a CLI flag (`--no-shell-format`), so that I can bypass this feature if it breaks my specific shell code or if I prefer manual formatting.
6. As a `snakefmt` developer, I want comprehensive tests for shell formatting, so that edge cases and complex shell code from existing tests do not regress.

## Implementation Decisions

- **Dependency:** Add `shfmt-py` as a required dependency in `pyproject.toml`. Note: Investigation shows `shfmt-py` only exposes the `bin/shfmt` binary, not a Python library API. Thus, we must invoke it via a subprocess call.
- **CLI Flag:** Add `--no-shell-format` to `snakefmt` CLI to disable shell formatting. Shell formatting is ON by default.
- **Module `snakefmt.shell_formatter`:**
  - Create a new deep module responsible for shell formatting.
  - Implement a regex-based masking strategy to replace `{variable}` with a safe identifier (e.g., `__SNAKEFMT_VAR_X__`) before calling `shfmt`.
  - Ensure the masking logic ignores double braces `{{` and `}}`, leaving them intact for `shfmt` to process as standard bash strings.
  - Invoke `shfmt` via `subprocess.run` with hardcoded sensible default arguments.
  - Revert the `__SNAKEFMT_VAR_X__` placeholders back to `{variable}`.
  - Gracefully handle `shfmt` errors by falling back to the original string.
- **Module `snakefmt.formatter`:**
  - Modify `Formatter.format_params` to check if `parameters.keyword_name == "shell"` and the `--no-shell-format` flag is false. If so, route the string content to `snakefmt.shell_formatter.format_shell_code` instead of passing it to `ast.parse`.

## Testing Decisions

- **What makes a good test:** Tests should verify the external behavior of formatting shell directives. The tests should ensure valid shell code is formatted, invalid shell code gracefully skips formatting, and Snakemake variables and escaped braces are handled flawlessly.
- **Module `tests.test_shell_formatter`:**
  - Unit tests for the new shell formatting logic in isolation.
  - Test cases for masking and unmasking Snakemake variables.
  - Test cases for edge cases like `awk '{{print $1}}'`.
  - Test cases for invalid shell syntax ensuring no crashes occur.
- **Module `tests.test_formatter`:**
  - Integration tests ensuring `Formatter` correctly routes `shell` directives.
  - Add tests using complex shell blocks from existing tests to ensure robustness.
  - Test the `--no-shell-format` flag behavior.

## Out of Scope

- Formatting non-shell directives like `run`, `script`, or `wrapper` using `shfmt`.
- Exposing `shfmt` configuration options to the user (e.g., in `pyproject.toml`).
- Replacing `black` for Python formatting.

## Further Notes

- `shfmt-py` acts as a binary distributor. The implementation will need to find the executable path reliably and use `subprocess`.

**Comment by mbhall88** [comment]
A first cut of shell-block formatting via `shfmt` has been implemented on the `feat/shfmt` branch — a PR will follow shortly. Sharing the design here so you can flag anything that needs to change before it lands.

**CLI surface**

- `-f` / `--format-shell` (default) and `-F` / `--no-format-shell` to opt out.
- Equivalent `format_shell = true|false` under `[tool.snakefmt]` in `pyproject.toml`.

**Behaviour**

- `shfmt` is invoked with `-i 4 -ci -bn` (four-space indentation, indented switch cases, binary operators may start a line).
- Snakemake `{var}` placeholders are masked before `shfmt` runs and restored afterwards. Escaped double-brace placeholders (`awk '{{print $1}}'`) are passed through unchanged.
- If `shfmt` cannot parse the shell body, `snakefmt` raises `InvalidShell` rather than silently skipping. Escape hatches are `-F` (whole run) or `# fmt: off` / `# fmt: on` (per block).

**Distribution**

`shfmt` is delivered via the [`shfmt-py`](https://github.com/MaxWinterstein/shfmt-py) wheel — no separate user-side install required. The reasoning for staying on `shfmt-py` rather than forking or building native Go bindings, plus the concrete triggers that would flip that decision, are written up in [ADR-0001](https://github.com/snakemake/snakefmt/blob/feat/shfmt/docs/adr/0001-shell-formatter-distribution.md) on the same branch.

Feedback on the CLI shape, defaults, or any of the above welcome before the PR opens.
