### ISSUE TITLE
python 3.12: unable to format inconsistent use of tabs and spaces

### ISSUE THREAD

**Issue by maarten-k** [snakemake/snakefmt#205]
I am testing snakemake to run with Python 3.12-rc3 by running the tests of snakemake itself.

I ran into the following error:

```
~/git/snakemake/tests/test05$ snakefmt -d Snakefile 
  File "<string>", line 27
    threads: 2
              ^
TabError: inconsistent use of tabs and spaces in indentation
```

This is expected since this is clearly in the [changelog of Python 3.12](https://docs.python.org/3.12/whatsnew/3.12.html#whatsnew312-porting-to-python312)

`Mixing tabs and spaces as indentation in the same file is not supported anymore and will raise a [TabError](https://docs.python.org/3.12/library/exceptions.html#TabError).
`

Snakemake itself is also unable to parse this file under Python 3.12.  Removing the tabs/spaces issue from the snakefile solves both problems, but lowers the usability of snakefmt/snakemake to remove these issues by hand.

**Comment by mbhall88** [comment]
So are you asking for snakefmt to resolve the tab/space issue for you?

**Comment by maarten-k** [comment]
The issue is that this error does not occur under Python 3.11 and does occur under Python 3.12.

**Comment by mbhall88** [comment]
Well `TabError` is raised because Python does not allow mixing tabs and spaces. (See [this SO answer](https://stackoverflow.com/a/45621723/5299417) for a nice explanation).

Maybe we need a discussion about whether or not it is `snakefmt`'s responsibility to deal with this. I'm a little bit hesitant to have `snakefmt` deal with this as I think it should be brought to the user's attention as it may indicate something going wrong in their editor or developer team.

In the meantime, seems like a lot of people use this to make the indentation consistent https://pypi.org/project/reindent/

**Comment by bricoletc** [comment]
I also think that it shouldn't be `snakefmt`'s responsibility
