### ISSUE TITLE
Black configuration is not used

### ISSUE THREAD

**Issue by kpj** [snakemake/snakefmt#73]
Consider the following Snakefile:
```python
rule all:
    input:
        foo='bar'
```

And the following configuration file:
```toml
[tool.black]
skip-string-normalization = 1

```

Then execute `snakefmt --compact-diff --config config.toml Snakefile`.

I would expect the file to pass formatting without any modifications.
However, it says:
```bash
=====> Diff for Snakefile <=====

--- original
+++ new
@@ -1,3 +1,3 @@
 rule all:
     input:
-        foo='bar'
+        foo="bar",

[INFO] All done 🎉
```

It seems like `black` does not know about the configuration parameters.

Compare this to executing `black --diff --config config.toml test.py` where `test.py` only contains `'fubar'`.
The output is (as expected) `All done! ✨ 🍰 ✨`.

**Comment by mbhall88** [comment]
Hmm, that's odd. I'll take a look next week.

Notes for future self:
- could be related to https://github.com/psf/black/issues/1667
- we definitely pass all of the config options to black https://github.com/snakemake/snakefmt/blob/8cbc95b1bf2ce746f37ab5c568d4c73d697ac7c1/snakefmt/formatter.py#L78

**Comment by mbhall88** [comment]
Ok @kpj I have a fix (I think) in https://github.com/mbhall88/snakefmt/commit/1f7ac818edf6d6cab47e858f07c8db134cea6d74

One thing for future reference, it is better to use booleans `true` rather than `1` in TOML. I found in once version of `black` that is actually failed if `1` was used.

There were two issues causing this bug:
1. We weren't passing the config past the CLI parsing if it didn't contain `[tool.snakefmt]`
2. When creating the `black.FileMode` object, it actually uses `string_normalization`, which is the inverse of the CLI arg `--skip-string-normalization` (so annoying). So I have added in some stuff to handle both flavours

Feel free to try out and see if you have any problems with it.

**Comment by kpj** [comment]
Awesome, thanks for taking a look!

> One thing for future reference, it is better to use booleans `true` rather than `1` in TOML. I found in one version of `black` that it actually failed if `1` was used.

Makes sense, will do. We should also amend this in snakefmt's README.

> Feel free to try out and see if you have any problems with it.

If I try the above example again, I get the output `[INFO] All done 🎉`
It seems to work nicely :)
